# docker-compose.yml
version: '3'

services:
  backend:
    build: ./backend
    container_name: 'benny-test-backend'
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./backend/:/app/
    ports:
      - "8001:8001"
    env_file: backend/.env

  frontend:
    build: ./frontend
    container_name: 'benny-test-frontend'
    volumes:
      - ./frontend/:/app/frontend
    command: npm start

  nginx:
    image: nginx:latest
    container_name: 'benny-test-nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5000:5000"
